"""
Step 3: Ablation instead of random sampling.

Standard Plackett-Burman design for N=8 runs, up to k=7 two-level factors,
generated by cyclic shifts of a base row plus one all-minus row (the classical
construction, e.g. Plackett & Burman 1946; see also Fawcett & Hoos on ablation
analysis for algorithm configuration, which motivates using a fractional design
rather than full factorial or random sampling here).

With 5 factors this design is resolution III: main effects are estimable and
unconfounded with each other, at the cost of confounding with two-way
interactions. That trade-off is accepted explicitly (see analysis/surrogate.py)
in exchange for needing only 8 configurations instead of 32.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent / "config"))
from axes import AXIS_ORDER

# Base generator row for PB(8): + + + - + - -
_BASE = [1, 1, 1, -1, 1, -1, -1]


def _cyclic_shifts(base):
    rows = []
    n = len(base)
    for shift in range(n):
        rows.append([base[(i - shift) % n] for i in range(n)])
    rows.append([-1] * n)
    return rows


def plackett_burman_8(k: int):
    """Returns an 8 x k matrix of +/-1, k <= 7."""
    assert 1 <= k <= 7
    full = _cyclic_shifts(_BASE)
    return [row[:k] for row in full]


def build_designs():
    k = len(AXIS_ORDER)
    matrix = plackett_burman_8(k)
    configs = []
    for row in matrix:
        cfg = {axis: (1 if v == 1 else 0) for axis, v in zip(AXIS_ORDER, row)}
        configs.append(cfg)
    return configs


if __name__ == "__main__":
    configs = build_designs()
    out_path = Path(__file__).parent / "configs.json"
    out_path.write_text(json.dumps(configs, indent=2))
    print(f"wrote {len(configs)} configurations to {out_path}")
    for i, c in enumerate(configs):
        print(i, c)
